spring:
  data:
    mongodb:
      uri: mongodb+srv://zl:password@zhuleitest.vsa3r7y.mongodb.net/
      database: test
#spring:
#  data:
#    mongodb:
#      username: testUser
#      password: password
#      database: test
#      port: 27017
#      host: 192.168.2.16
#      authentication-database: admin